export const ADD_TASK = "ADD_TASK";
export const COMPLETED_TASK = "COMPLETED_TASK";
export const INCREAMENT_COMPLETED_TASK = "INCREAMENT_COMPLETED_TASK";
export const DECREAMENT_COMPLETED_TASK = "DECREAMENT_COMPLETED_TASK";
export const DECREAMENT_TOTAL_TASK = "DECREAMENT_TOTAL_TASK";
export const INCREAMENT_TOTAL_TASK = "INCREAMENT_TOTAL_TASK";
export const REMOVE_TASK = "REMOVE_TASK";